### ISSUE TITLE
Improved handling when running again with already started instance

### ISSUE THREAD

**Issue by dzek69** [dail8859/NotepadNext#296]
I'm using Linux AppImage (the beta version from here: https://github.com/dail8859/NotepadNext/issues/81#issuecomment-1367378181)

When I run the app again I'd expect two things (let me know if you prefer to have this issue splitted into two, I will create separate issue then):
- focus should be moved to Notepad Next
- if current file is modified or non-empty file then new empty file should be opened

currently focus stays on whatever was focused and nothing changes inside Notepad Next, like I never run the command

**Comment by dail8859** [comment]
> focus should be moved to Notepad Next

See #149 for a full discussion. In short, I've made a few attempts but not sure if a valid solution exists. I would certainly like to this get fixed but as far as I can tell it may not be possible.

> if current file is modified or non-empty file then new empty file should be opened

Hmmm, this I'll have to give this more thought. I can't recall other editing tools that do this (but maybe I've just never used it this way). The rough use-case would be to just ensure the application is running, which is the point of (attempting) to bring the application to the foreground.

What is the exact expectation here? "I need a blank document to start typing and I don't care if the application is already opened?"

**Comment by dzek69** [comment]
> See https://github.com/dail8859/NotepadNext/issues/149 for a full discussion

Okay, gonna keep the conversation about this there.

> What is the exact expectation here? "I need a blank document to start typing and I don't care if the application is already opened?"

Something like that.

I need to note down something quickly, so I need a new blank canvas to type. I don't want to look through all the monitors and windows for the app, I just press Win key, type "notepad", hit enter and I can type.

**Comment by dzek69** [comment]
> As far as I know this kind of thing isn't built into Notepad++

Hah, you're right. I was damn sure that this is default behavior of N++. It still sound like a nice feature, that's easy to add 😅 

> Here's a slight alternative proposal to try to achieve the behavior...a new command line argument -NewFile

Hmm... I'd prefer to set this up in Preferences. It could be non-default of course. The `-NewFile` sounds ok too, but IMO it's better as an addition to Preferences, to override it if needed. Personally  I restrain from creating CLI-only options until something is reall-super-advanced or it's super useful to be able to override it for single use without modifying Preferences.

> is this functionality useful until it properly focuses on the primary instance?

probably not really, because "the flow" is already broken.

But (there is always a "but"):
on the other hand - speaking of CLI - I can and temporarrly I will fix the bringing to front myself (until it's properly fixed in the NN code) - by setting a shortcut to bash script that first runs NN and then brings it to the front. So personally I would appreciate this feature even now (and if the bringing to front problem is Linux only - then other OS users could benefit from it as well)

**Comment by dail8859** [comment]
> It still sound like a nice feature, that's easy to add

CLI...not too bad. Preference dialog, still not too bad but requires UI, additional flag to modify behavior, saving/loading the setting, translating UI text, etc.

> probably not really, because "the flow" is already broken.

That was my thinking as well.

---

So let me ask a question...and please understand this isn't meant to belittle the need or request, but more to justify putting time into either a CLI option, or to the (future) preference dialog...

What does this save in the end...an extra shortcut press (`Ctrl+N`) when launching the app with the intent of creating a new blank document?

The more I think about it the harder it is to justify this specific use case. There's also some things to consider about if the app is the primary vs secondary instance, if it loads the previous session, should it check if there's a temp document already, and other things like that. If `--NewFile` was treated as a very dumb flag of "tell the primary instance to execute File > New" (and ideally bring it to the foreground) then that seems more straight forward and reasonable.

If there is another application that has this kind of behavior, I'd be interested to try it out to get a feel for it.

**Comment by dzek69** [comment]
yeah, maybe you're right. For such low manpower it's not worth spending too much time on this. 

> If --NewFile was treated as a very dumb flag of "tell the primary instance to execute File > New" (and ideally bring it to the foreground) then that seems more straight forward and reasonable.

I'll be happy with that only then, but then it starting to sound like a feature I'll be the only one to use, then it makes no sense at all

> If there is another application that has this kind of behavior, I'd be interested to try it out to get a feel for it.

Yeah, even a few (but that's cheating, because they are all forks):
- `xed`, the basic editor that comes with Linux Mint Cinnamon. It just spawns new file, without any checks.
- Pluma (which is where xed was forked from) is smarter, it will only open new file if there is unmodified and unsaved file opened - this is what I asked for initially
- gedit (a base for Pluma) is again dumb, and will open a new file each time, no matter what

Microsoft is adding tabs to Notepad soon (according to leaks) I wonder how they will handle it. My bet is it will create another instance anyway.

**Comment by dail8859** [comment]
I'll close this issue for now. Its not quite as straightforward as I had hoped. If this kind of solution would be more applicable to a larger group of users then maybe that would be a good time to reconsider it.
